config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :profiles do
    member do
      put "like" => "profiles#upvote"
      put "unlike" => "profiles#downvote"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :messages
  resources :categories
  resources :vinyls do
    resources :offers
  end

  resources :user, :only => [:index, :edit] do
    resources :offers, :only => [:destroy]
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end


  get "offers_list", to: "home#offers_list"
  get "dashboard", to: "home#dashboard"
  
  get '/users/:user_id/offers', to: 'offers#user_offers', as: 'my_offers'

  post '/users/:user_id/offers/:id/accept', to: 'offers#accept', as: :swap_accepted
  
  post '/users/:user_id/offers/:id/decline', to: 'offers#decline', as: :swap_declined


  delete '/vinyls/:vinyl_id/offers/:id', to: 'offers#destroy', as: 'destroy'
  
  
  get "vinylslist", to: "shared#vinyls"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  acts_as_votable
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  geocoded_by :address
  after_validation :geocode

  def address
    [municipality, state].compact.join(', ')
  end


  paginates_per 8

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update destroy upvote downvote]
  before_action :authenticate_user!
  

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    @vinyls = Vinyl.all.order("created_at DESC").where(user_id: @profile.user.id).page(params[:page]).per(4)
  end

  def new
    @profile = current_user.build_profile
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = current_user.build_profile(profile_params)
    @user = User.find(current_user)
    @profile = Profile.new(@user)
    @profile.save

    # respond_to do |format|
    #   if @profile.save
    #     format.html { redirect_to @profile, notice: "Profile was successfully created." }
    #     format.json { render :show, status: :created, location: @profile }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @profile.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote
    if @profile.user_id != current_user.id
      @profile.upvote_from current_user
      redirect_to profile_path
    end
  end

  def downvote
    if @profile.user_id != current_user.id
      @profile.downvote_from current_user
      redirect_to profile_path
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:avatar, :bio, :latitude, :longitude, :state, :municipality, :user_id, :collectionist_name)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
	<% if profile.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

		<ul>
		<% profile.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
		</div>
	<% end %>

	<div class="container">
		<div class="field">
			<%= form.label :avatar %><br/>
			<%= form.file_field :avatar %>
		</div>

		<div class="field">
			<%= form.hidden_field :user_id%>
		</div>
		
		<div class="field">
			<%= form.label :bio %><br/>
			<%= form.text_area :bio, placeholder:"Ej: Intercambio por punk..." %>
		</div>
		
		<div class="field">
			<%= form.label :state %><br/>
			<select id="regiones" style="width: 200px;" class="<%= form.text_field :state %>"></select>
		</div>

		<div class="field">
			<%= form.label :municipality %><br/>
			<select id="comunas" class="<%= form.text_field :municipality %>"></select>
		</div>

		<div class="actions">
			<%= form.submit class: "btn btn-outline-dark btn-sm"%>
		</div>
	</div>
<% end %>

<script>
var RegionesYcomunas = {
	regiones: [
		{
			NombreRegion: "Arica y Parinacota",
			comunas: ["Arica", "Camarones", "Putre", "General Lagos"]
		},
		{
			NombreRegion: "Tarapacá",
			comunas: [
				"Iquique",
				"Alto Hospicio",
				"Pozo Almonte",
				"Camiña",
				"Colchane",
				"Huara",
				"Pica"
			]
		},
		{
			NombreRegion: "Antofagasta",
			comunas: [
				"Antofagasta",
				"Mejillones",
				"Sierra Gorda",
				"Taltal",
				"Calama",
				"Ollagüe",
				"San Pedro de Atacama",
				"Tocopilla",
				"María Elena"
			]
		},
		{
			NombreRegion: "Atacama",
			comunas: [
				"Copiapó",
				"Caldera",
				"Tierra Amarilla",
				"Chañaral",
				"Diego de Almagro",
				"Vallenar",
				"Alto del Carmen",
				"Freirina",
				"Huasco"
			]
		},
		{
			NombreRegion: "Coquimbo",
			comunas: [
				"La Serena",
				"Coquimbo",
				"Andacollo",
				"La Higuera",
				"Paiguano",
				"Vicuña",
				"Illapel",
				"Canela",
				"Los Vilos",
				"Salamanca",
				"Ovalle",
				"Combarbalá",
				"Monte Patria",
				"Punitaqui",
				"Río Hurtado"
			]
		},
		{
			NombreRegion: "Valparaíso",
			comunas: [
				"Valparaíso",
				"Casablanca",
				"Concón",
				"Juan Fernández",
				"Puchuncaví",
				"Quintero",
				"Viña del Mar",
				"Isla de Pascua",
				"Los Andes",
				"Calle Larga",
				"Rinconada",
				"San Esteban",
				"La Ligua",
				"Cabildo",
				"Papudo",
				"Petorca",
				"Zapallar",
				"Quillota",
				"Calera",
				"Hijuelas",
				"La Cruz",
				"Nogales",
				"San Antonio",
				"Algarrobo",
				"Cartagena",
				"El Quisco",
				"El Tabo",
				"Santo Domingo",
				"San Felipe",
				"Catemu",
				"Llaillay",
				"Panquehue",
				"Putaendo",
				"Santa María",
				"Quilpué",
				"Limache",
				"Olmué",
				"Villa Alemana"
			]
		},
		{
			NombreRegion: "Región del Libertador Gral. Bernardo O’Higgins",
			comunas: [
				"Rancagua",
				"Codegua",
				"Coinco",
				"Coltauco",
				"Doñihue",
				"Graneros",
				"Las Cabras",
				"Machalí",
				"Malloa",
				"Mostazal",
				"Olivar",
				"Peumo",
				"Pichidegua",
				"Quinta de Tilcoco",
				"Rengo",
				"Requínoa",
				"San Vicente",
				"Pichilemu",
				"La Estrella",
				"Litueche",
				"Marchihue",
				"Navidad",
				"Paredones",
				"San Fernando",
				"Chépica",
				"Chimbarongo",
				"Lolol",
				"Nancagua",
				"Palmilla",
				"Peralillo",
				"Placilla",
				"Pumanque",
				"Santa Cruz"
			]
		},
		{
			NombreRegion: "Región del Maule",
			comunas: [
				"Talca",
				"ConsVtución",
				"Curepto",
				"Empedrado",
				"Maule",
				"Pelarco",
				"Pencahue",
				"Río Claro",
				"San Clemente",
				"San Rafael",
				"Cauquenes",
				"Chanco",
				"Pelluhue",
				"Curicó",
				"Hualañé",
				"Licantén",
				"Molina",
				"Rauco",
				"Romeral",
				"Sagrada Familia",
				"Teno",
				"Vichuquén",
				"Linares",
				"Colbún",
				"Longaví",
				"Parral",
				"ReVro",
				"San Javier",
				"Villa Alegre",
				"Yerbas Buenas"
			]
		},
		{
			NombreRegion: "Región del Biobío",
			comunas: [
				"Concepción",
				"Coronel",
				"Chiguayante",
				"Florida",
				"Hualqui",
				"Lota",
				"Penco",
				"San Pedro de la Paz",
				"Santa Juana",
				"Talcahuano",
				"Tomé",
				"Hualpén",
				"Lebu",
				"Arauco",
				"Cañete",
				"Contulmo",
				"Curanilahue",
				"Los Álamos",
				"Tirúa",
				"Los Ángeles",
				"Antuco",
				"Cabrero",
				"Laja",
				"Mulchén",
				"Nacimiento",
				"Negrete",
				"Quilaco",
				"Quilleco",
				"San Rosendo",
				"Santa Bárbara",
				"Tucapel",
				"Yumbel",
				"Alto Biobío",
				"Chillán",
				"Bulnes",
				"Cobquecura",
				"Coelemu",
				"Coihueco",
				"Chillán Viejo",
				"El Carmen",
				"Ninhue",
				"Ñiquén",
				"Pemuco",
				"Pinto",
				"Portezuelo",
				"Quillón",
				"Quirihue",
				"Ránquil",
				"San Carlos",
				"San Fabián",
				"San Ignacio",
				"San Nicolás",
				"Treguaco",
				"Yungay"
			]
		},
		{
			NombreRegion: "Región de la Araucanía",
			comunas: [
				"Temuco",
				"Carahue",
				"Cunco",
				"Curarrehue",
				"Freire",
				"Galvarino",
				"Gorbea",
				"Lautaro",
				"Loncoche",
				"Melipeuco",
				"Nueva Imperial",
				"Padre las Casas",
				"Perquenco",
				"Pitrufquén",
				"Pucón",
				"Saavedra",
				"Teodoro Schmidt",
				"Toltén",
				"Vilcún",
				"Villarrica",
				"Cholchol",
				"Angol",
				"Collipulli",
				"Curacautín",
				"Ercilla",
				"Lonquimay",
				"Los Sauces",
				"Lumaco",
				"Purén",
				"Renaico",
				"Traiguén",
				"Victoria"
			]
		},
		{
			NombreRegion: "Región de Los Ríos",
			comunas: [
				"Valdivia",
				"Corral",
				"Lanco",
				"Los Lagos",
				"Máfil",
				"Mariquina",
				"Paillaco",
				"Panguipulli",
				"La Unión",
				"Futrono",
				"Lago Ranco",
				"Río Bueno"
			]
		},
		{
			NombreRegion: "Región de Los Lagos",
			comunas: [
				"Puerto Montt",
				"Calbuco",
				"Cochamó",
				"Fresia",
				"FruVllar",
				"Los Muermos",
				"Llanquihue",
				"Maullín",
				"Puerto Varas",
				"Castro",
				"Ancud",
				"Chonchi",
				"Curaco de Vélez",
				"Dalcahue",
				"Puqueldón",
				"Queilén",
				"Quellón",
				"Quemchi",
				"Quinchao",
				"Osorno",
				"Puerto Octay",
				"Purranque",
				"Puyehue",
				"Río Negro",
				"San Juan de la Costa",
				"San Pablo",
				"Chaitén",
				"Futaleufú",
				"Hualaihué",
				"Palena"
			]
		},
		{
			NombreRegion: "Región Aisén del Gral. Carlos Ibáñez del Campo",
			comunas: [
				"Coihaique",
				"Lago Verde",
				"Aisén",
				"Cisnes",
				"Guaitecas",
				"Cochrane",
				"O’Higgins",
				"Tortel",
				"Chile Chico",
				"Río Ibáñez"
			]
		},
		{
			NombreRegion: "Región de Magallanes y de la AntárVca Chilena",
			comunas: [
				"Punta Arenas",
				"Laguna Blanca",
				"Río Verde",
				"San Gregorio",
				"Cabo de Hornos (Ex Navarino)",
				"AntárVca",
				"Porvenir",
				"Primavera",
				"Timaukel",
				"Natales",
				"Torres del Paine"
			]
		},
		{
			NombreRegion: "Región Metropolitana de Santiago",
			comunas: [
				"Cerrillos",
				"Cerro Navia",
				"Conchalí",
				"El Bosque",
				"Estación Central",
				"Huechuraba",
				"Independencia",
				"La Cisterna",
				"La Florida",
				"La Granja",
				"La Pintana",
				"La Reina",
				"Las Condes",
				"Lo Barnechea",
				"Lo Espejo",
				"Lo Prado",
				"Macul",
				"Maipú",
				"Ñuñoa",
				"Pedro Aguirre Cerda",
				"Peñalolén",
				"Providencia",
				"Pudahuel",
				"Quilicura",
				"Quinta Normal",
				"Recoleta",
				"Renca",
				"San Joaquín",
				"San Miguel",
				"San Ramón",
				"Vitacura",
				"Puente Alto",
				"Pirque",
				"San José de Maipo",
				"Colina",
				"Lampa",
				"TilVl",
				"San Bernardo",
				"Buin",
				"Calera de Tango",
				"Paine",
				"Melipilla",
				"Alhué",
				"Curacaví",
				"María Pinto",
				"San Pedro",
				"Talagante",
				"El Monte",
				"Isla de Maipo",
				"Padre Hurtado",
				"Peñaflor"
			]
		}
	]
};

jQuery(document).ready(function () {
	var iRegion = 0;
	var htmlRegion =
		'<option value="sin-region">Seleccione región</option><option value="sin-region">--</option>';
	var htmlComunas =
		'<option value="sin-region">Seleccione comuna</option><option value="sin-region">--</option>';

	jQuery.each(RegionesYcomunas.regiones, function () {
		htmlRegion =
			htmlRegion +
			'<option value="' +
			RegionesYcomunas.regiones[iRegion].NombreRegion +
			'">' +
			RegionesYcomunas.regiones[iRegion].NombreRegion +
			"</option>";
		iRegion++;
	});

	jQuery("#regiones").html(htmlRegion);
	jQuery("#comunas").html(htmlComunas);

	jQuery("#regiones").change(function () {
		var iRegiones = 0;
		var valorRegion = jQuery(this).val();
		var htmlComuna =
			'<option value="sin-comuna">Seleccione comuna</option><option value="sin-comuna">--</option>';
		jQuery.each(RegionesYcomunas.regiones, function () {
			if (RegionesYcomunas.regiones[iRegiones].NombreRegion == valorRegion) {
				var iComunas = 0;
				jQuery.each(RegionesYcomunas.regiones[iRegiones].comunas, function () {
					htmlComuna =
						htmlComuna +
						'<option value="' +
						RegionesYcomunas.regiones[iRegiones].comunas[iComunas] +
						'">' +
						RegionesYcomunas.regiones[iRegiones].comunas[iComunas] +
						"</option>";
					iComunas++;
				});
			}
			iRegiones++;
		});
		jQuery("#comunas").html(htmlComuna);
	});
	jQuery("#comunas").change(function () {
		if (jQuery(this).val() == "sin-region") {
			alert("selecciones Región");
		} else if (jQuery(this).val() == "sin-comuna") {
			alert("selecciones Comuna");
		}
	});
	jQuery("#regiones").change(function () {
		if (jQuery(this).val() == "sin-region") {
			alert("selecciones Región");
		}
	});
});

</script>

app/views/profiles/_modal_profile.html.erb
<%= form_with(model: @profile, local: true) do |form| %>
    <div class="modal" id="<%= @profile.id %>" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title">Editing Profile</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="field">
                            <%= form.label :avatar %><br/>
                            <%= form.file_field :avatar %>
                        </div>

                        <div class="field">
                            <%= form.hidden_field :user_id%>
                        </div>
                    
                        <div class="field">
                            <%= form.label :bio %><br/>
                            <%= form.text_area :bio %>
                        </div>
                    
                        <div class="field">
                            <%= form.label :state %><br/>
                            <%= form.text_field :state %>
                        </div>

                        <div class="field">
                            <%= form.label :municipality %><br/>
                            <%= form.text_field :municipality %>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                  <%= form.submit "Save", class: "btn btn-primary btn-sm"%>
                </div>
            </div>
        </div>
    </div>
<% end %>








               

app/views/profiles/edit.html.erb
<section class="page-section">
    <div class="container">
        <div class="about-heading-content">
        <div class="row">
                <div class="col-xl-6 col-xs-10 mx-auto">
                    <div class="bg-faded shadow rounded p-5">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-lower">Editing Profile</span>
                        </h2>
                        <p>
                            <%= render 'form', profile: @profile %>

                            <%= link_to 'Back', @profile %> 
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 

app/views/profiles/edit.js.erb
# $('#modalProfile .modal-content').html('<%= j render "profiles/modal_profile", profile: @profile %>');
# $('#modalProfile').modal('show');
# console.log('javascript works')

app/views/profiles/index.html.erb
<div class="container table-responsive mx-auto py-4 page-section cta-inner bg-faded">
  <h1 class="text-center mb-5">Profiles</h1>
  <table class="table table-strip table-hover mx-auto">
    <thead class="text-center">
      <tr class="mb-3"> 
        <th>Avatar</th>
        <th>Name</th>
        <th>Bio</th>
        <th>State</th>
        <th>Municipality</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @profiles.each do |profile| %>
        <tr>
            <td><%= image_tag(profile.avatar.url, :class => "avatar rounded-circle img-fluid")%></td>
            <td><%= profile.user.collectionist_name %></td>
            <td><%= profile.bio %></td>
            <td><%= profile.state%></td>
            <td><%= profile.municipality %></td>
            <% if current_user.admin? %>
                <td><%= link_to 'Go to Profile', profile %></td>
                <td><%= link_to 'Edit', edit_profile_path(profile)%></td>
                <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%else%>
                <td><%= link_to 'Go to Profile', profile %></td>
            <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/profiles/new.html.erb
<div class="container" >

    <h1>New Profile</h1>

    <%= render 'form', profile: @profile %>

    <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<div class="shadow-lg main rounded">
    <div class="row">
      <div class="col-md-6 picture">
          <center><%= image_tag(@profile.avatar.url, :class => "rounded-circle img-fluid") %></center>
      </div>
      <div class="col-sm-6 details">
        <center>
            <p class="name"><b><%= @profile.user.collectionist_name%></b> <i class="material-icons tick">check_circle</i></p>
        </center>
        <center>
            <p class="email"><b><%= @profile.user.email%></b>
        </center>
        <center>
            <p class="email"><b>Role: <%= @profile.user.role%></b>
        </center>
        <center>
            <p><i class="fa fa-map-marker fa-lg" aria-hidden="true"></i>
            <%= @profile.municipality%>, <%= @profile.state %> </p>
        </center>
        <center class="caption mb-2">                                                                                        
            <%= link_to like_profile_path(@profile), class: "like", method: :put do %>
                <button type="button" class="btn btn-link" aria-label="Left Align">
                <span class="fa fa-thumbs-up"></span> 
                <span class="badge"><%= @profile.get_upvotes.size %></span>
                </button> 
            <% end %>      
            <%= link_to unlike_profile_path(@profile), class: "like", method: :put do %>
                <button type="button" class="btn btn-link" aria-label="Left Align">
                <span class="fa fa-thumbs-down"></span> 
                <span class="badge"><%= @profile.get_downvotes.size %></span>
                </button> 
            <% end %>                  
        </center>
      </div>
      <div class="col-sm-12 details">
        <hr>
        <center>
          <h5 class="pt-4"><strong>My Fav Music to Exchange</strong></h5>
              <p data-profile-id="<%= @profile.id %>"><%= @profile.bio%></p>  
          <br>
        </center>
        <hr>
      </div>
      <table class="table">
          <tr>
              <td>
              <center>
                  <p><b><%=@profile.user.vinyls.count%></b></p>
                  <h6>Vinyls</h6w>
              </center>
              </td>
              <td>
              <center>
                  <p><b><%=@profile.user.vinyls.where(status: "swapped").count%></b></p>
                  <h6>Swaps</h6>
              </center>
              </td>
          </tr>
      </table>
      <center><%= link_to 'Edit', edit_profile_path(@profile), class:"waves-effect waves-light btn edit"%></center>  
    </div>    
</div>
<br><br><br><br><br><br><br>
<div class="col-sm-6">

</div>

<div class="col-md-12">

<!-- Nav tabs -->
<ul class="container nav nav-tabs mt-5 border-warning border-2" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link nav-profile active" id="messages-tab" data-bs-toggle="tab" data-bs-target="#messages" type="button" role="tab" aria-controls="messages" aria-selected="false">My Record Collection</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link nav-profile" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings" type="button" role="tab" aria-controls="settings" aria-selected="false">Messages</button>
  </li>
</ul>

<!-- Tab panes -->
<div class="container tab-content mt-5">
  <div class="tab-pane active" id="messages" role="tabpanel" aria-labelledby="messages-tab">
  
    <div class="container px-4 px-lg-5 mt-5 bg-transparent border border-warning border-2">
    <div class="d-grid gap-2 d-md-flex flex-row justify-content-md-end mt-2">
      <div class="input-group p-2 bd-highlight justify-content-md-end">
          <%= link_to new_vinyl_path do %>
            <i class="fa fa-plus-circle fa-3x" aria-hidden="true" data-bs-toggle="tooltip" data-bs-placement="top" title="Add a New Vinyl"></i>
          <% end %>
      </div>
    </div>
      <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-4 justify-content-center">
        <% @vinyls.each do |vinyl| %>
          <div class="col mb-5">
          <div class="card h-100 shadow justify-content-center mt-5">
              <!-- Vinyl image -->
              <% if vinyl.image.attached? %>
                <%= link_to vinyl do %>
                  <%= image_tag vinyl.image, class: "card-img-top", alt: "#{vinyl.title}" %>
                <% end  %>
              <% end %>
              <div class="card-body">
                <!-- vinyl name-->
                <h5 class="card-title fw-bolder text-center "><%= vinyl.title %></h5>
                <h6 class="card-title text-center"><%= vinyl.author %></h6>
              </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item text-muted text-center"><%= vinyl.condition %></li>
                </ul>
              <!-- agregar vinyl actions --> 
              <div class="card-body mx-auto"> 
              <% if vinyl.status === "available" %>            
                <%= link_to new_vinyl_offer_path(vinyl), method: :get do %>
                  <button type="button" class="btn btn-outline-dark btn-sm shadow mt-auto">Swap Request</button>
                <% end %><br />  
              <% else %>
                <%= button_tag "Swapped", disabled: true, class: "btn btn-outline-secondary btn-sm mt-auto"%>
              <% end %> 
              </div>
            </div>
          </div>
        <% end %>   
      </div>
        <div class="pagination justify-content-center">
          <h5 class="m-4 text-center p-3">
            <span><%= paginate @vinyls %></span>
          </h5>
        </div>
    </div>  
  </div>
  <div class="tab-pane" id="settings" role="tabpanel" aria-labelledby="settings-tab">
      <center><%= image_tag('seccion-en-construccion.png')%></center>
  </div>
  <%= render 'modal_profile' %>
</div>


<br><br><br><br><br><br><br><br><br><br><br><br>




  

app/views/profiles/update.js.erb
# $('#modalProfile').modal('hide');
# $('p[data-profile-id="' + <%= @profile.id %> + '"]').replaceWith('<%= j render "profiles/profile", profile: @profile %>');



   