config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :profiles do
    member do
      put "like" => "profiles#upvote"
      put "unlike" => "profiles#downvote"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :messages
  resources :categories
  resources :vinyls do
    resources :offers
  end

  resources :user, :only => [:index, :edit] do
    resources :offers, :only => [:destroy]
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end


  get "offers_list", to: "home#offers_list"
  get "dashboard", to: "home#dashboard"
  
  get '/users/:user_id/offers', to: 'offers#user_offers', as: 'my_offers'

  post '/users/:user_id/offers/:id/accept', to: 'offers#accept', as: :swap_accepted
  
  post '/users/:user_id/offers/:id/decline', to: 'offers#decline', as: :swap_declined


  delete '/vinyls/:vinyl_id/offers/:id', to: 'offers#destroy', as: 'destroy'
  
  
  get "vinylslist", to: "shared#vinyls"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vinyl.rb
class Vinyl < ApplicationRecord
  belongs_to :user
  has_many :offers, dependent: :destroy
  has_and_belongs_to_many :categories
  has_one_attached :image

  enum status: [:available, :swapped]

  paginates_per 12

  validates :title, :author, :description, :status, presence: true
  validate :image_attached
  validate :description_length

  private

  def image_attached
    unless image.attached?
      errors.add(:image, "must be attached")
    end
  end

  def description_length
    if description.present? && description.length > 300
      errors.add(:description, "exceeds the character limit (300)")
    end
  end

end

app/controllers/vinyls_controller.rb
class VinylsController < ApplicationController
  before_action :set_vinyl, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /vinyls or /vinyls.json
  def index
    @vinyls = Vinyl.with_attached_image.all.order("created_at desc").page(params[:page])

    @q = Vinyl.includes(:user).ransack(params[:q])
    @vinyls = @q.result(distinct: true).page(params[:page])
  end

  # GET /vinyls/1 or /vinyls/1.json
  def show
    @vinyl = Vinyl.find(params[:id])
    @owner = @vinyl.user_id
    @profile = Profile.find_by(user_id: @owner)  

  end

  # GET /vinyls/new
  def new
    @vinyl = Vinyl.new
  end

  # GET /vinyls/1/edit
  def edit
  end

  # POST /vinyls or /vinyls.json
  def create
      @vinyl = current_user.vinyls.build(vinyl_params)
      @vinyl.user = current_user

    respond_to do |format|
      if @vinyl.save
        format.html { redirect_to vinyl_url(@vinyl), notice: "Vinyl was successfully created." }
        format.json { render :show, status: :created, location: @vinyl }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinyls/1 or /vinyls/1.json
  def update
    respond_to do |format|
      if @vinyl.update(vinyl_params)
        format.html { redirect_to vinyl_url(@vinyl), notice: "Vinyl was successfully updated." }
        format.json { render :show, status: :ok, location: @vinyl }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinyls/1 or /vinyls/1.json
  def destroy
    @vinyl = Vinyl.find(params[:id])
    @vinyl.destroy

    respond_to do |format|
      format.html { redirect_to vinyls_url, notice: "Vinyl was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vinyl
      @vinyl = Vinyl.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vinyl_params
      params.require(:vinyl).permit(:title, :author, :released_date, :format, :description, :status, :condition, :category, :image, :user_id, :municipality, :state,  {category_ids: []})
    end
end

app/helpers/vinyls_helper.rb
module VinylsHelper
    def genres_options
        Vinyl
          .connection
          .select_rows('select distinct unnest(genre) from vinyls')
          .flatten
    end
end

app/views/vinyls/_form.html.erb
 <%= form_with(model: vinyl, local: true) do |form| %>
  <% if vinyl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vinyl.errors.count, "error") %> prohibited this vinyl from being saved:</h2>

      <ul>
      <% vinyl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <%= form.label "Vinyl image" %><br />
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :title %><br />
      <%= form.text_field :title, autofocus: true%>
    </div>

    <div class="field">
      <%= form.label :author %><br />
      <%= form.text_field :author%>
    </div>

    <div class="field">
      <%= form.label :released_date %><br />
      <%= form.date_field :released_date %>
    </div>

    <div class="field">
      <%= form.label :format %><br />
      <%= form.text_field :format%>
    </div>

    <div class="field">
      <%= form.label :description %><br />
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :status %><br />
      <%= form.select(:status, Vinyl.statuses.keys.to_a) %> 
    </div>

    <div class="field">
      <%= form.label :condition %><br />
      <%= form.select(:condition, options_for_select(['new','used']))%>
    </div>

    <div class="field>
      <%= form.hidden_field :user_id %>        
    </div>
    <br>
   <div class="row">
    <div class="field col-md-4">
    <%= form.label :categories, "Categories:" %><br />
        <%= form.collection_check_boxes(:category_ids,
                                        Category.all,
                                        :id,
                                        :genre) do |b| %>
        <%= b.label class:"label-checkbox" do%>
            <%=b.check_box + b.text%>
        <%end%>
    <% end %>
  </div>
  </div>
    <br>
    <br>    

    <div class="actions">
      <%= form.submit class: "btn btn-outline-dark btn-sm"  %>
    </div>
<% end %>

app/views/vinyls/_search.html.erb
<% # No se utilizó %>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="container">
    <div class="offcanvas-header">
      <h3 class="offcanvas-title justify-content-center" id="offcanvasExampleLabel">Filters</h3>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
    
      <form>
        <%= search_form_for @q do |f|%>
          <div class="mb-3">
            <%= f.label  :released_date_eq, "Release Year: "%>
            <%= f.date_field :released_date_eq, placeholder: "1970...", class: 'form-control form-control-sm' %>
            <%= f.submit 'Buscar', class: "btn btn-outline-dark btn-sm"  %>
          </div>
          <div class="mb-3">
            <%= f.label  :genre_eq, "Genre: "%>
            <% genre_array = Category.all.map {|c| [c.genre, c.id]} %>
            <%= f.select :genre_eq, options_for_select(genre_array, @q.genre_eq), include_blank: "All", class: "input-search form-control form-control-sm"%>
            <%= f.submit 'Filter', class: "btn btn-outline-dark btn-sm mb-3"%>
          </div>
          <div class="mb-3">
            <%= f.label "Near to you: "%></br>
            <input type="range" class="form-range inputDiv i1" min="1" max="200" id="customRange2"><span> km </span>
            <%= f.submit 'Filter', class: "btn btn-outline-dark btn-sm" %></span>
          </div>
            <%= link_to 'Limpiar', vinyls_path, class: 'btn btn-primary btn-sm text-center justify-content-center', style:"color: black !important; border: 1px solid; margin-left: auto;"%>
        <% end %>
      </form> 
   </div>
  </div>  
</div>

app/views/vinyls/edit.html.erb
<section class="page-section">
  <div class="container">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded shadow-lg rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower">Editing Vinyl</span>
            </h2>
            <p>

              <%= render 'form', vinyl: @vinyl %>
              <%= link_to 'Back', @vinyl,  class: "btn btn-outline-dark btn-sm" %>
           </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> 

app/views/vinyls/index.html.erb
<section class="page-section ">
  <div class="container mx-auto cta">     
    <h2 class="section-heading mb-5 cta-inner bg-faded text-center rounded p-2">
      <span class="section-heading-lower">Record's Box <%= image_tag("box.png", size: "35") %></span>
    </h2>
   
    <div class="py-4 page-section cta-inner bg-faded">
      <div class="d-grid gap-2 d-md-flex flex-row justify-content-md-center mt-2">
        <%= search_form_for @q do |f| %>
          <div class="search input-group p-2 bd-highlight">
            <%= f.search_field :title_or_author_cont, placeholder:"Search for band/album...", class: "form-control form-control-sm", value: params[:q]&.dig(:title_or_author_cont)&.downcase %>
            <%= f.submit "Search", class: "btn btn-outline-dark shadow btn-sm" %>
          </div>
          <p> Release Date: </p>
          <div class="search input-group mb-3 mt-2">
           
            <%= f.date_field :released_date_eq, placeholder: "1970...", class: 'form-control form-control-sm'%>
            <%= f.submit 'Filter', class: "btn btn-outline-dark shadow  btn-sm"  %>
          </div>
          
          <%= link_to 'Clean All', vinyls_path, class: 'btn btn-primary shadow btn-sm text-center justify-content-center'%>
        <%end%>
      </div>
      <div class="input-group p-2 bd-highlight justify-content-md-end mt-5">
          <%= sort_link(@q, :condition, default_order: :asc) do %>
            <strong style="text-decoration: underline">Sort by condition</strong>
          <% end %>

          <%= link_to new_vinyl_path do %>
            <button class="btn btn-outline-dark shadow  btn-sm ms-3" type="button">Add Vinyls <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-vinyl-fill" viewBox="0 0 16 16">
            <path d="M8 6a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm0 3a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4 8a4 4 0 1 0 8 0 4 4 0 0 0-8 0z"/>
            </svg></button>
          <% end %>
      </div> 
       

        <%= render 'shared/vinylslist' %>       
      </p> 

      <div class="pagination justify-content-center">
        <h5 class="m-4 text-center p-3">
          <span><%= paginate @vinyls %></span>
        </h5>
      </div>
    </div>
  </div>
</section>

app/views/vinyls/new.html.erb
<section class="page-section">
  <div class="container">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-7 mx-auto">
          <div class="bg-faded shadow-lg border border-warning rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower text-center">New Vinyl</span>
            </h2>
            <div class="mx-auto">
              <%= render 'form', vinyl: @vinyl %>
              <%= link_to 'Back', vinyls_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> 

app/views/vinyls/show.html.erb
<br><br>
<section class="pt-5 mb-5">
  <div class="container">
    <div class="card mb-3 shadow-lg bg-faded">
      <div class="row g-0">
        <div class="col-md-6">
          <%= image_tag @vinyl.image, style:"width: 612px", class: "img-fluid mb-md-0", alt: "#{@vinyl.title}" %>
        </div>
        <div class="col-md-6">
          <div class="card-body vinyl-desc p-5 bg-faded shadow-lg section-heading">
            <h5 class="section-heading-upper"><%= @vinyl.author %></h5>
            <h2 class="section-heading-lower mb-3"><%= @vinyl.title %></h2>
            <p>
                <strong>Description:</strong>
                <%= @vinyl.description %>
            </p>
            <p>
                <strong>Condition: </strong>
                <%= @vinyl.condition %>
            </p>
            <p>
                <strong>Release date:</strong>
                <%= @vinyl.released_date %>
            </p>
            <p>
                <strong>Format:</strong>
                <%= @vinyl.format %>
            </p>
            <p>
                <strong>Status:</strong>
                <%= @vinyl.status %>
            </p>
            <p>
                <strong>Owner:</strong>
                <%= link_to @vinyl.user.collectionist_name, profile_path(@profile)%>          
            </p>
            <p>
                <strong>Genres:</strong>
                <%= @vinyl.categories.map(&:genre).join(', ') %>  
            </p>

            <div class="d-flex pt-4">
        <!--Botón de swap está deshabilitado cuando se concretó un trueque-->
              <% if @vinyl.status === "available" %>
                <%= form_for :offer, url: new_vinyl_offer_path(@vinyl), method: :get do |f| %>
                  <%= f.hidden_field :vinyl_id, value: @vinyl.id %>
                  <%= f.submit "Swap Request", class: "btn btn-outline-dark mt-auto" %>
                <% end %>
              <% else %>
                <%= button_tag "Swapped", disabled: true, class: "btn btn-outline-dark mt-auto"%>
              <% end %>
            </div>
            <!--Condicional el dueño puede editar y borrar-->
            <% if @vinyl.user_id == current_user.id || current_user.admin? %>
              <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-5">
                <%= link_to edit_vinyl_path(@vinyl) do %>
                  <button class="btn btn-outline-dark btn-sm" type="button">Edit vinyl</button>
                <% end %>
                <!-- Enlace delete recarga el show y no borra-->
                <%= link_to @vinyl, method: :delete, data: {confirm: "Are you sure?"} do %>
                  <button class="btn btn-outline-dark btn-sm" type="button">Delete Vinyl</button>
                <% end %>
              </div>
            <% end %>
            <div class="mt-3">
              <%= link_to '<< Back to Vinyls', vinyls_path %> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <br><br><br><br>
  <!--<section class="page-section cta d-none d-lg-block">-->
  <!--<div class="container">-->   
    <!--<h2 class="section-heading mb-4 cta-inner bg-faded text-center rounded p-2">-->
      <!--<span class="section-heading-lower">Related Vinyls</span>-->
    <!--</h2-->
    <!-- Agregar lista de vinilos similares-->
 <!-- </div>-->
<!--</section>-->