config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :profiles do
    member do
      put "like" => "profiles#upvote"
      put "unlike" => "profiles#downvote"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :messages
  resources :categories
  resources :vinyls do
    resources :offers
  end

  resources :user, :only => [:index, :edit] do
    resources :offers, :only => [:destroy]
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end


  get "offers_list", to: "home#offers_list"
  get "dashboard", to: "home#dashboard"
  
  get '/users/:user_id/offers', to: 'offers#user_offers', as: 'my_offers'

  post '/users/:user_id/offers/:id/accept', to: 'offers#accept', as: :swap_accepted
  
  post '/users/:user_id/offers/:id/decline', to: 'offers#decline', as: :swap_declined


  delete '/vinyls/:vinyl_id/offers/:id', to: 'offers#destroy', as: 'destroy'
  
  
  get "vinylslist", to: "shared#vinyls"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
  <div class="container">
    <%= link_to 'VinylSwapp', root_path, class: "navbar-brand text-uppercase fw-bold d-lg-none" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <% if user_signed_in? %>
          <li class="nav-item px-lg-4 px-lg-4">
            <%= link_to 'All Vinyls', vinyls_path, class: "nav-link text-uppercase" %>
          </li>
          <li class="nav-item px-lg-4 px-lg-4">
            <%= link_to 'Collectionists', profiles_path, class: "nav-link text-uppercase" %>
          </li>
          
          <% if current_user.admin? %>
            <li class="nav-item px-lg-4">
              <%= link_to 'Swaps Request', offers_list_path, class: "nav-link text-uppercase" %>
            </li> 
          <% else %>
            <li class="nav-item px-lg-4">
              <%= link_to 'My Swaps Request', my_offers_path(current_user.id, @offers), class: "nav-link text-uppercase" %>
            </li> 
          <% end %>
          <li class="nav-item dropdown">
            <span class="nav-link dropdown-toggle text-uppercase" id="userOptions" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Logged in as <%= current_user.email %>
            </span>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="userOptions">
              <li>
                <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %> 
              </li>
              <%if current_user.profile == nil %>
                <li>
                  <%= link_to 'Create Your Profile', new_profile_path, class: "dropdown-item" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "My Profile", current_user.profile, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "My Record Collection",current_user.profile, class: "dropdown-item" %>
                </li>
              <% end %>
                <li>
                  <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
                </li>
                <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
         <% else %>
          <li class="nav-item px-lg-4">
            <%= link_to 'Home', root_path, class: "nav-link text-uppercase" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-uppercase" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-uppercase" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_vinylslist.html.erb
<div class="container px-4 px-lg-5 mt-5">
  <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <% @vinyls.each do |vinyl| %>
      <div class="col mb-5">
       <div class="card h-100 shadow justify-content-center">
          <!-- Vinyl image -->
          <% if vinyl.image.attached? %>
            <%= link_to vinyl do %>
              <%= image_tag vinyl.image.variant(resize: 222), class: "card-img-top", alt: "#{vinyl.title}" %>
            <% end  %>
          <% end %>
          <div class="card-body">
            <!-- vinyl name-->
            <h5 class="card-title fw-bolder text-center "><%= vinyl.title %></h5>
            <h6 class="card-title text-center"><%= vinyl.author %></h6>
          </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-muted text-center"><%= vinyl.condition %></li>
            </ul>
          <!-- agregar vinyl actions --> 
          <div class="card-body mx-auto"> 
          <% if vinyl.status === "available" %>            
            <%= link_to new_vinyl_offer_path(vinyl), method: :get do %>
              <button type="button" class="srequest btn btn-outline-dark btn-sm shadow mt-auto">Swap Request</button>
            <% end %><br />  
          <% else %>
            <%= button_tag "Swapped", disabled: true, class: "btn btn-outline-secondary btn-sm mt-auto"%>
          <% end %> 
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>    