config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :profiles do
    member do
      put "like" => "profiles#upvote"
      put "unlike" => "profiles#downvote"
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :messages
  resources :categories
  resources :vinyls do
    resources :offers
  end

  resources :user, :only => [:index, :edit] do
    resources :offers, :only => [:destroy]
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end


  get "offers_list", to: "home#offers_list"
  get "dashboard", to: "home#dashboard"
  
  get '/users/:user_id/offers', to: 'offers#user_offers', as: 'my_offers'

  post '/users/:user_id/offers/:id/accept', to: 'offers#accept', as: :swap_accepted
  
  post '/users/:user_id/offers/:id/decline', to: 'offers#decline', as: :swap_declined


  delete '/vinyls/:vinyl_id/offers/:id', to: 'offers#destroy', as: 'destroy'
  
  
  get "vinylslist", to: "shared#vinyls"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :offeredvinyl, class_name: "Vinyl", foreign_key: :offeredvinyl_id
  belongs_to :receivervinyl, class_name: "Vinyl", foreign_key: :vinyl_id
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :user, class_name: 'User', foreign_key: :owner_id

  enum offer_state: [:pending, :accepted, :declined]

  validates_uniqueness_of :offeredvinyl_id, :scope => :vinyl_id
  validate :cant_interact_myself

  def cant_interact_myself
    if self.user_id == self.owner_id
      errors.add(:offer, "can't send you an offer to yourself")
    end
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ show edit update destroy ]
  before_action :set_user_vinyls, only: %i[ new create ]
  before_action :set_vinyl
  before_action :authenticate_user!

  # GET /offers or /offers.json
  def index  
    @vinyl = Vinyl.find(params[:vinyl_id])
    @offers = @vinyl.offers.includes(:user).all.order("created_at desc")
  end

  # GET /offers/1 or /offers/1.json
  def show
    #@user = @offer.user_id == current_user ? @offer.owner_id : @offer.user_id
  end

  # GET /offers/new
  def new
    @vinyl = Vinyl.find(params[:vinyl_id])
    @offer = Offer.new
    @offer.owner_id = @vinyl.user_id
    @offered_vinyl = current_user.vinyls.pluck(:title, :id)
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id
    @offer.owner_id = params[:offer][:owner_id].to_i
    @offer.offer_state = "pending"
    @offer.vinyl_id = params[:vinyl_id].to_i
    @offered_vinyl = current_user.vinyls.pluck(:title, :id)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to my_offers_path(current_user.id), notice: "Offer was successfully sended to the vinyl owner." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to vinyl_offer_path(@offer.vinyl_id, @offer.id), notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to my_offers_path(@offer.user_id, @offers), notice: "Offer was successfully canceled." }
      format.json { head :no_content }
    end
  end

  def user_offers
    @received_offers = Offer.where(owner_id: current_user.id).where.not(offer_state: ["declined", "accepted"])
    @offers_sent= current_user.offers.where.not(offer_state: "accepted")
    @user_id = current_user.id
    @swaps_other = Offer.where(owner_id: @user_id, offer_state: "accepted")
    @swaps_user = Offer.where(user_id: @user_id, offer_state: "accepted") 
    
   
     
    #@offers = Offer.find_by(params[:id])
    #@user = User.find(@offers.owner_id)

    #@user_owner = @offers.owner_id
    #@user_sender = @offers.user_id
    #@profile_owner = Profile.find_by(user_id: @user)  
    #@profile_sender = Profile.find_by(user_id: @user_sender) 
  end 

  def accept
    @user = current_user
    
    offer = Offer.find(params[:id])
    offered_vinyl = Vinyl.find(offer.offeredvinyl_id)
    other_vinyl = Vinyl.find(offer.vinyl_id)
    if offer && offer.update(offer_state: "accepted")
      
      offered_vinyl.update(user_id: current_user.id)
      other_vinyl.update(user_id: offer.user_id)
      offered_vinyl.update(status: "swapped")
      other_vinyl.update(status: "swapped")

      Offer.where(vinyl_id: offer.vinyl_id).where.not(id: offer.id).update_all(offer_state: "declined")
      Offer.where(offeredvinyl_id: offer.vinyl_id).where.not(id: offer.id).update_all(offer_state: "declined")
      Offer.where(vinyl_id: offer.offeredvinyl_id).where.not(id: offer.id).update_all(offer_state: "declined")
      Offer.where(offeredvinyl_id: offer.offeredvinyl_id).where.not(id: offer.id).update_all(offer_state: "declined")
      
      flash[:notice] = "Congratulations! You have done a vinyl swap"
      #OfferNotifierMailer.send_completed_swap_email(current_user).deliver_now
      redirect_to my_offers_path(current_user.id, @offers)  

     
    else 
      flash[:error] = "No se pudo concretar el swap"
      redirect_to vinyls_path
    end
  end

  def decline
      offer = Offer.find(params[:id])
      if offer 
          if offer.update(offer_state: "declined")

            flash[:alert] = "You have refused a vinyl swap request"  
              redirect_to root_path
          end
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find_by(id: params[:id]) #coloqué id:
    end

    def set_vinyl
      @vinyl = Vinyl.find_by_id(params[:vinyl_id])
    end

    def set_user_vinyls
      @user_vinyls = current_user.vinyls
    end

  

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:offeredvinyl_id, :vinyl_id, :offer_state, :user_id, :owner_id, :end_date)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_with(model: [@vinyl, offer], local: true) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :offeredvinyl_id, "Offered Vinyl" %></strong>
    <%= form.select :offeredvinyl_id, options_for_select(current_user.vinyls.where(:status=> 'available').pluck(:title, :id))%>   
  </div>

  <div class="field">
    <strong><%= form.label "Chosen Vinyl:  "%></strong>
    <%= @vinyl.title + ' - ' + @vinyl.author%>
  </div>

  <div class="field">
    <strong><%= form.label :owner_id, 'Owner: ' %></strong>
    <%= @vinyl.user.collectionist_name %>
  </div>

 <div class="field">
   <%= form.hidden_field :owner_id, value: @offer.owner_id %>
 </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-dark btn-sm" %>
  </div>
<% end %>

app/views/offers/destroy.js.erb
$('#offer_<%= @offer.id %>').fadeOut();

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', vinyl_offer_path(@vinyl.id, @offer.id)%> |
<%= link_to 'Back', vinyl_offers_path(:vinyl_id)%>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Offered vinyl</th>
      <th>Chosen Vinyl</th>
      <th>Owner</th>
      <th>State</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.offeredvinyl.title %></td>
        <td><%= offer.receivervinyl.title %></td>
        <td><%= offer.user.collectionist_name%></td>
        <td><%= offer.offer_state %></td>
        <td><%= offer.end_date %></td>
        <td><%= link_to 'Show', vinyl_offer_path(@vinyl.id, offer.id)%></td>
        <td><%= link_to 'Edit', edit_vinyl_offer_path(offer.vinyl_id, offer.id) %></td>
        <td><%= button_to 'Destroy', destroy_path(@vinyl.id, offer.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_vinyl_offer_path(@vinyl) %>

app/views/offers/new.html.erb
<section class="page-section">
  <div class="container">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-md-9 mx-auto">
          <div class="bg-faded shadow-lg border border-warning rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower text-center">New Offer</span>
            </h2>
            <p class="justify-content-center">
              <%= render 'form', offer: @offer %>
              <%= link_to 'Back', vinyls_path %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> 

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Offeredvinyl:</strong>
  <%= @offer.offeredvinyl.title + ' - ' + @offer.offeredvinyl.author%> 
</p>

<p>
  <strong>Receivervinyl:</strong>
  <%= @offer.receivervinyl.title + ' - ' + @offer.receivervinyl.author %>
</p>

<p>
  <strong>Offer state:</strong>
  <%= @offer.offer_state %>
</p>

<%= link_to 'Edit', edit_vinyl_offer_path(@offer.vinyl_id, @offer) %> |
<%= link_to 'Back', my_offers_path(current_user.id, @offers) %>

app/views/offers/swapped_vinyls.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="container border border-warning border-2">
 <h1 class="text-center mt-4"> Swaps List</h1>
    <br>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>OFFERED VINYL</th>
            <th>SENDER</th>
            <th>CHOSEN VINYL</th>
            <th>OWNER</th>
            <th>STATE</th>
            <th>END DATE</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @swapped_vinyls.each do |swap| %>
            <tr>
              <td><%= swap.offeredvinyl.title %></td>
              <td><%= swap.user_id %></td>
              <td><%= swap.receivervinyl.title %></td>
              <td><%= swap.owner_id %></td>
              <td><%= swap.offer_state %></td>
              <td><%= swap.end_date %></td>
              <td><%= button_to 'Cancel'%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

<br>
<br>

app/views/offers/user_offers.html.erb
<br>
<div class="container border border-warning border-2 bg-light">
 <h1 class="text-center mt-4"> Offers Received</h1>
    <br>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>PROPOSED VINYL</th>
            <th>YOUR VINYL</th>
            <th>SENDER</th>
            <th>STATE</th>
            <th>DATE</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @received_offers.each do |offer| %>
            <tr>
              <td><%= link_to offer.offeredvinyl.title %></td>
              <td><%= offer.receivervinyl.title%></td>
              <td><%= link_to User.find(offer.user_id).collectionist_name%></td>
              <td><%= offer.offer_state %></td>
              <td><%= offer.created_at.strftime("%Y-%m-%d")  %></td>
              <% if offer.offer_state === "pending" %> 
                <td><%= button_to 'Accept', swap_accepted_path(offer.user_id, offer.id), class:"btn btn-warning shadow"%></td>
                <td><%= button_to 'Decline', swap_declined_path(offer.user_id, offer.id), class:"btn btn-warning shadow"%></td>
              <%else%>
                <td><%= button_to 'Accept', swap_accepted_path(offer.user_id, offer.id), disabled: true, class:"btn btn-btn-light shadow"%></td>
                <td><%= button_to 'Decline', swap_declined_path(offer.user_id, offer.id), disabled: true, class:"btn btn-btn-light shadow"%></td>
              <%end%>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

<br>
<br>

<div class="container border border-warning border-2 bg-light text-center">
  <h1 class="text-center mt-4">Offers Sent</h1>
    <br>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>YOUR VINYL</th>
            <th>REQUESTED VINYL</th>
            <th>OWNER</th>
            <th>STATE</th>
            <th>DATE</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @offers_sent.each do |offer| %>
            <tr>
              <td><%= offer.offeredvinyl.title %></td>
              <td><%= offer.receivervinyl.title %></td>
              <td><%= link_to offer.user.collectionist_name%></td>
              <td><%= offer.offer_state %></td>
              <td><%= offer.created_at.strftime("%Y-%m-%d") %></td>
              <td><%= button_to 'Cancel', user_offer_path(offer.user_id, offer.id), method: :delete, data: {confirm: "Are you sure?"}%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
<br>
<br>

<% if @swaps_other %>
  <div class="container border border-warning border-2 bg-light text-center">
  <h1 class="text-center mt-4">Your Swaps</h1>
      <br>
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>YOUR VINYL</th>
              <th>SWAPPED VINYL</th>
              <th>SWAPPED WITH</th>
              <th>DATE</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @swaps_other.each do |swap| %>
              <tr>
                <td><%= swap.offeredvinyl.title %></td>
                <td><%= swap.receivervinyl.title %></td>
                <td><%= link_to User.find(swap.user_id).collectionist_name%></td>
                <td><%= swap.created_at.strftime("%Y-%m-%d")  %></td>
              </tr>
            <% end %>
          </tbody>
          <br>
          <% if @swaps_user %>
            <tbody>
              <% @swaps_user.each do |swap| %>
                <tr>
                  <td><%= swap.offeredvinyl.title%></td>
                  <td><%= swap.receivervinyl.title %></td>
                  <td><%= link_to swap.user.collectionist_name%></td>
                  <td><%= swap.created_at.strftime("%Y-%m-%d")  %></td>
                </tr>
              <% end %>
            </tbody>
          <% end %>
        </table>
      </div>
  </div>
  <br>
  <br>
<% end %>